//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WWList
    {
        public int WWLID { get; set; }
        public int UserID { get; set; }
        public int MovieID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual User User { get; set; }
    }
}
